name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y lsof gawk shellcheck
    
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install shellcheck
    
    - name: Check dependencies
      run: make check
    
    - name: Run shellcheck
      run: shellcheck devports install.sh
    
    - name: Run basic tests
      run: make test
    
    - name: Test installation
      run: |
        make install-local
        export PATH="$HOME/.local/bin:$PATH"
        devports --version
        devports --help